name: Translate README

on:
  push:
    branches:
      - main

jobs:
  translate-readme:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install the 'trans' command line tool to interact with Google Translate
      - name: Install translation tool
        run: |
          sudo apt-get update
          sudo apt-get install translate-shell

      # Translate README.md to Spanish
      - name: Translate README to Spanish
        run: |
          cat README.md | trans -b :es > README_es.md

      # Commit the translated README_es.md
      - name: Commit translated README
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README_es.md
          git commit -m "Add translated README in Spanish"
          git push